### ISSUE TITLE
Failed to get CHud instance

### ISSUE THREAD

**Issue by nazaryman** [Mevasss/warthunder-sindrome#1]
Failed to get CHud instance

after build it show that error when open

**Comment by Mevasss** [comment]
Make sure that you run the game without anti-cheat, or add your own communication with the driver if you want to use it with anti-cheat. The latest update has not changed the offsets.
![image](https://github.com/Mevasss/warthunder-sindrome/assets/105033463/132ed194-a909-4069-b0b3-d3bfe2c0ceb6)

**Comment by Mevasss** [comment]
Disable easy anti cheat ( delete eac launcher from x32 folder and open game from x64 folder)

**Comment by Mevasss** [comment]
m3vas3

**Comment by nazaryman** [comment]
hastey8199


there are no username such 
m3vas3
